[[plugins]]
repo = 'Shougo/dein.vim'

### fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'zxqfl/tabnine-vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'mhinz/vim-signify'

### ariline
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# lsp
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-lsp-icons'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
# [[plugins]]
# repo = 'prabirshrestha/async.vim'
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'

# [[plugins]]
# repo = 'github/copilot.vim'

[[plugins]]
repo = 'w0rp/ale'
