[[plugins]]
repo = 'Shougo/dein.vim'

### fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'

# [[plugins]]
# repo = 'zxqfl/tabnine-vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'mhinz/vim-signify'

### ariline
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'w0rp/ale'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'

[[plugins]]
repo = 'tpope/vim-rhubarb'

# [[plugins]]
# repo = 'gbprod/yanky.nvim'
